config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/list'
  get 'todos/new'
  post 'todos', to:'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'todo_edit'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as: 'todo_complete'

  root 'todos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new(todo_params)
        @todo.save
        redirect_to todos_path
    end

    def show
        @todo = Todo.find(params[:id])   
    end

    def edit
        @todo = Todo.find(params[:id])
    end

    def update
        @todo = Todo.find(params[:id])
        @todo.update(todo_params)
        redirect_to todos_path
    end

    def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy
        redirect_to todos_path
    end

    def complete
        @todo = Todo.find(params[:id])
        @todo.update_attribute(:completed, true)
        @todo.save
        redirect_to todos_path
    end

    def list
        @todos = Todo.all
    end

    private
    def todo_params
        params.require(:todo).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>TodoApp</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Hidden brand</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <li class="nav-item nav-link">
        <%=link_to "Index", todos_path %>
      </li>
      <li class="nav-item nav-link">
      <%=link_to "List", todos_list_path %>
    </li>
    <li class="nav-item nav-link">
    <%=link_to "New", todos_new_path %>
  </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f| %>
    <%= f.label :description, "Titulo Todo" %>
    <%= f.text_field :description %>
    <%= f.submit "Enviar" %>
 <% end %>   

app/views/todos/edit.html.erb
<%= render 'form' %>

app/views/todos/index.html.erb
<% @todos.each do |t| %>
    <%= t.description %>
    <%= link_to 'mostrar', t %>
    <%= link_to 'editar', todo_edit_path(t) %>
    <%= link_to 'borrar', t, method: :delete %>
    <%= link_to 'completado', todo_complete_path(t) %>
<% end %>

<%= link_to 'create todo', todos_new_path %> 
    
  
  

app/views/todos/list.html.erb
<div class="container m-5">
  <div class="row">
    <div class="col-md-6">
        <h1>INCOMPLETO</h1> 
        <% @todos.each do |t| %>
            <% if t.completed? == false %>
                <%= t.description %>
            <% end %>
        <% end %>
    </div>
    <div class="col-md-6">
        <h1>COMPLETADO</h1>
        <% @todos.each do |t| %>
            <% if t.completed? == true %>
            <%= t.description %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/todos/new.html.erb
<%= render 'form' %>

app/views/todos/show.html.erb
<%= @todo.description %>
<%= @todo.completed? %>